name: corpus
version: 0.1.0
description: A tool to calculate the API usage for a package.
repository: https://github.com/dart-lang/ecosystem

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^3.4.1
  args: ^2.0.0
  cli_util: ^0.3.0
  collection: ^1.16.0
  http: ^0.13.0
  path: ^1.8.0
  surveyor:
    git:
      url: https://github.com/pq/surveyor
  yaml: ^3.0.0

dev_dependencies:
  checks:
    git:
      url: https://github.com/dart-lang/test
      path: pkgs/checks
  lints: '>=1.0.0 <3.0.0'
  test: ^1.16.0
  test_descriptor: ^2.0.0
