name: quest
description: Test package upgrades against the ecosystem.
repository: https://github.com/dart-lang/ecosystem/tree/main/pkgs/quest

publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.1
  firehose: ^0.9.3
  io: ^1.0.4
  path: ^1.9.1

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.24.0
