name: quest
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0-129.0.dev

# Add regular dependencies here.
dependencies:

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.24.0
