name: quest
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/dart-lang/ecosystem/tree/main/pkgs/quest

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  io: ^1.0.4
  path: ^1.9.1

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.24.0
