name: puppy
description: A package for miscellaneous Dart CLI tools.
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  build_cli_annotations: ^2.1.0
  io: ^1.0.5

dev_dependencies:
  build_cli: ^2.2.4
  build_runner: ^2.4.14
  dart_flutter_team_lints: ^3.0.0

executables:
  puppy:
