include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  exclude:
    - test_data/*

linter:
  rules:
    - prefer_final_locals
    - unnecessary_parenthesis
    - prefer_expression_function_bodies
    - document_ignores
    - parameter_assignments
