name: trebuchet
description: A tool for hurling packages into monorepos.

publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.5.0
  path: ^1.9.0

dev_dependencies:
  dart_flutter_team_lints: ^3.2.0
  test: ^1.24.0
