name: repo_manage
description: Miscellaneous issue, repo, and PR query tools.

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.0
  collection: ^1.17.0
  github: ^9.11.0
  graphql: ^5.0.0
  path: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
