name: package:canary

permissions: read-all

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/canary.yml'
      - 'pkgs/canary/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/canary.yml'
      - 'pkgs/canary/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: pkgs/canary

env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          channel: main
          cache: true

      - run: dart pub get

      - run: dart analyze --fatal-infos

      - run: dart format --output=none --set-exit-if-changed .

      - run: dart test
