# A CI configuration to check for licenses in Dart files.

name: License Check

# Callers of this workflow should use it as follows:
#
# name: License Check
# on:
#   pull_request:
#     branches: [ main ]
#     types: [opened, synchronize, reopened, labeled, unlabeled]
#   push:
#     tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
# jobs:
#   check_licenses:
#     uses: dart-lang/ecosystem/.github/workflows/check_licenses.yml@main

jobs:
  check_licenses:
    # These permissions are required for authentication using OIDC and to enable
    # us to create comments on PRs.
    permissions:
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: stable

      - name: Install firehose
        run: dart pub global activate firehose

      - name: Check package file licenses
        if: ${{ github.event_name == 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.number }}
          PR_LABELS: "${{ join(github.event.pull_request.labels.*.name) }}"
        run: dart pub global run firehose --check_licenses
