name: package:corpus

permissions: read-all

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/corpus.yml'
      - 'pkgs/corpus/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/corpus.yml'
      - 'pkgs/corpus/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: pkgs/corpus

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, dev]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260
        with:
          sdk: ${{ matrix.sdk }}

      - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - run: dart pub get

      - run: dart analyze --fatal-infos

      - run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'dev' }}

      - run: dart test
