name: Groundskeeper Internal

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  tidy:
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        package:
          - blast_repo
          - canary
          - corpus
          - dart_flutter_team_lints
          - firehose
          - repo_manage
          - sdk_triage_bot
          - trebuchet
    uses: ./.github/workflows/groundskeeper.yml
    with:
      directory: pkgs/${{ matrix.package }}
      branch: auto-tidy-${{ matrix.package }}
      title: 'Tidy: package:${{ matrix.package }}'
    secrets: inherit
