# A CI configuration to check PR health.

name: Health:License
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  health:
    uses: ./.github/workflows/health.yaml
    with:
      local_debug: true
      coverage_web: false
      upload_coverage: false
      checks: license
