name: package:puppy

permissions: read-all

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/puppy.yml'
      - 'pkgs/puppy/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/puppy.yml'
      - 'pkgs/puppy/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

defaults:
  run:
    working-directory: pkgs/puppy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [3.6, dev]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c
        with:
          sdk: ${{ matrix.sdk }}

      - run: dart pub get
      - run: dart analyze --fatal-infos
      - run: dart format --output=none --set-exit-if-changed .
        if: ${{ matrix.sdk == 'dev' }}
      # TODO: enable when there are tests!
      #- run: dart test
