name: Tidy Codebase

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at 00:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  tidy:
    permissions:
      contents: write
      pull-requests: write
    uses: ./.github/workflows/reusable_tidy.yml
    secrets: inherit
